@startuml

title CardPage

Page <|-- CardPage
CardPage o-- Header
CardPage *-- ButtonSber
CardPage *-- CardList
CardPage *-- UserfundCart

CardPage <-- CardService
CardPage <-- Route
CardPage <-- Router


class Header <extend cl.Control> {
    renderCorrectTitle()
}

class ButtonSber <extends cl.gButton.Button> {
    dispose()
}

class CardList {
    renderCards()
}

class UserfundCart {
    show()
    hide()
}

class CardService {
    getCard()
    getFundsByAssociatedId()
    getFundEntitiesById()
    getDirectionsByAssociatedId()
}

class Route {
    CARD
}

class Router <extend cl.Router> {
    changeLocation()
}


class Page <extends cl.Control>

@enduml
