@startuml

title CardPage

Page <|-- CardPage

CardPage o-- Header

CardPage *-- ButtonSber
CardPage *-- CardList
CardPage *-- UserfundCart

CardPage <-- CardService
CardPage <-- Route
CardPage <-- Router


class Header <extend cl.Control> {
    renderCorrectTitle()
}

class ButtonSber <extends cl.gButton.Button> {
    dispose()
}

class CardList <extend cl.Control> {
    renderCards()
}

class UserfundCart <extend cl.Control> {
    show()
    hide()
}

class CardService {
    {static} getCard()
    {static} getFundsByAssociatedId()
    {static} getFundEntitiesById()
    {static} getDirectionsByAssociatedId()
}

class Route {
    {static} String CARD
}

class Router <extend cl.Router> {
    changeLocation()
}

class Page <extends cl.Control>

@enduml
