@startuml

title SV-55 b-donate-page

Page <|-- DonatePage
DonatePage *--  cl.Tab
DonatePage *--  DonationFixedBlock
DonatePage *--  DonationPercentBlock

DonatePage --> Router
DonatePage --> UserService

DonationFixedBlock *-- Button
DonationFixedBlock *-- Input

DonationPercentBlock *-- Button
DonationPercentBlock *-- Input
DonationPercentBlock *-- Slider

UserService --> Request

class Slider {
    enable()
    disable()
    getValue()    
}

class Router <extend cl.Router> {
    use()
    changeLocation()
    getMaskByUrl()
    parseMaskDataFromUrl()
}

class UserService {
    isUserLoggedIn()
}

class Input <extend cl.Input> {
    setValue()
    enable()
    disable()
    isValid()
    validate()
}

class Request {
    init()
    send()
}

class DonationFixedBlock <extend cl.Control>
class DonationPercentBlock <extend cl.Control>
class Button <extend cl.Button>

class Page  <extend cl.Control>


@enduml