@startuml

title SV-43 b-list-page

Page <|-- ListPage
ListPage o-- Header
ListPage *-- UserBlock
ListPage *-- ListTab
ListPage "2" *-- CardList
ListPage --> Router
ListPage --> UserService

Header *-- Icon
Header *-- Button
Header --> Router
Header --> Request

UserBlock *-- Button

CardList "0..*" *-- Card

UserService --> Request

class CardList <extend cl.Control> {
    renderCards()
}

class UserService {
    isUserLoggedIn()
    removeEntity()
    addEntity()
}

class ListTab <extend cl.Tab> {
    getContentTabs()
    setActiveTab()
    resizeActiveTab()
    createIcon()
}

class Header <extend cl.Control> {
    renderCorrectTitle()
    renderCorrectHelp()
    renderButton()
    renderListPageTitle()
}

class Router <extend cl.Router> {
    enable()
    use()
    changeLocation()
    getMaskByUrl()
    parseMaskDataFromUrl()
}

class UserService {
    isUserLoggedIn()
}

class UserBlock <extend cl.Control>
class Button <extend cl.Button>
class Page  <extend cl.Control>
class Request {
    init()
    send()
}


@enduml