SberVmeste -up-|> cl.Control
SberVmeste *--  HeaderManager
SberVmeste *-- PageManager

SberVmeste *-- Controller
SberVmeste --> Router

Controller o-- HeaderManager
Controller o-- PageManager

HeaderManager *-- Header
PageManager --> Router
PageManager *-- "0..*" Page

Page o-- Header

    
class Router <extend cl.Router> {
    use()
    changeLocation()
    getMaskByUrl()
    parseMaskDataFromUrl()
}

class HeaderManager <extend cl.ContentManager> {
    setProfileHeader()
    setChoiceHeader()
    setCardHeader()
    setListHeader()
    getCurrentHeader()
}

class PageManager <extend cl.ContentManager> {
    setCurrentPage()
    getCurrentPage()
    getLocation()
}

class Header <extend cl.Control> {
    renderCorrectTitle()
    renderCorrectHelp()
    renderButton()
    renderListPageTitle()
}

class Controller {
    actionStart()
    actionListPage()
    actionTest()
    actionDisplayCategoryCard()
    actionProfilePage()
    actionRegistrationPage()
    actionDonate()
    actionPayment()
    actionManageUserfund()
}


@enduml